/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPapeleraRouteImport } from './routes/_authenticated/papelera'
import { Route as AuthenticatedNuevoRouteImport } from './routes/_authenticated/nuevo'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedAsistenteRouteImport } from './routes/_authenticated/asistente'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPapeleraRoute = AuthenticatedPapeleraRouteImport.update({
  id: '/papelera',
  path: '/papelera',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNuevoRoute = AuthenticatedNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAsistenteRoute = AuthenticatedAsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/asistente': typeof AuthenticatedAsistenteRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/nuevo': typeof AuthenticatedNuevoRoute
  '/papelera': typeof AuthenticatedPapeleraRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/asistente': typeof AuthenticatedAsistenteRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/nuevo': typeof AuthenticatedNuevoRoute
  '/papelera': typeof AuthenticatedPapeleraRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/asistente': typeof AuthenticatedAsistenteRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/nuevo': typeof AuthenticatedNuevoRoute
  '/_authenticated/papelera': typeof AuthenticatedPapeleraRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/asistente'
    | '/inventario'
    | '/nuevo'
    | '/papelera'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/asistente' | '/inventario' | '/nuevo' | '/papelera' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/asistente'
    | '/_authenticated/inventario'
    | '/_authenticated/nuevo'
    | '/_authenticated/papelera'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/papelera': {
      id: '/_authenticated/papelera'
      path: '/papelera'
      fullPath: '/papelera'
      preLoaderRoute: typeof AuthenticatedPapeleraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nuevo': {
      id: '/_authenticated/nuevo'
      path: '/nuevo'
      fullPath: '/nuevo'
      preLoaderRoute: typeof AuthenticatedNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asistente': {
      id: '/_authenticated/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AuthenticatedAsistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAsistenteRoute: typeof AuthenticatedAsistenteRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedNuevoRoute: typeof AuthenticatedNuevoRoute
  AuthenticatedPapeleraRoute: typeof AuthenticatedPapeleraRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAsistenteRoute: AuthenticatedAsistenteRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedNuevoRoute: AuthenticatedNuevoRoute,
  AuthenticatedPapeleraRoute: AuthenticatedPapeleraRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
